### PR TITLE
Fix rcpp rmd bug

### PR DESCRIPTION
**Pull request by gowerc**
This PR is dependent / branched off #333 

**What problem did you solve?**

#334

**(If you have)Screenshot**

image

Screenshot shows that syntax highlighting now works for rcpp blocks and not cpp blocks (as per the supported languages spec (here)[https://bookdown.org/yihui/rmarkdown/language-engines.html] but also shows the syntax highlighting for the R block is maintained.

There was a slight complication in that the syntax highlighting for the R block was being falsely matched and applied to the Rcpp block (as it starts with R) so added some stricter regex to the R block to prevent this false match.

### CODE REVIEW

**Comment by renkun-ken** [comment]
For `{rcpp}` chunk, it works as expected. However, according to the https://bookdown.org/yihui/rmarkdown/language-engines.html, `{Rcpp}` should work too but it does not:

image

while both `{r}` and `{R}` chunks work:

image

**Comment by gowerc** [comment]
@renkun-ken  - O good spot, will update

Though interestingly you've shown there that the syntax highlighting is maintained for ```r   (rather than ```{r}) however this isn't valid for knitr.  Am wondering if we should stop the syntax highlighting here to give a visual cue to users that they haven't formatted it properly ?  (can make this a separate issue if you'd prefer)

**Comment by gowerc** [comment]
Following up on this some more  apparently `rcpp` isn't valid, it will only render `Rcpp`

image

**Comment by renkun-ken** [comment]
Interesting finding. `{rcpp}` actually is not working? Then I guess we should not provide syntax highlighting for it as it does not work.

**Comment by gowerc** [comment]
Just withdrawing the PR whilst I still iterate on it + other markdown changes

**Pull request closed without merging**
