### PR TITLE
No remove blank or comment lines

### LINKED ISSUE #312: Sending multi-line string removes lines starting with hash
Sending the following multi-line string to terminal removes `# hello` which is mistakenly treated as comment:

```r
text <- "
# hello
this is new #hello
"
```

Instead the following is actually sent to terminal:

```
> text <- " 
  this is new #hello 
  "
```

### PR DESCRIPTION
**Pull request by renkun-ken**
**What problem did you solve?**

Closes #312 

**(If you do not have screenshot) How can I check this pull request?**

Test with the following code:

```r
text <- "line1"

text <- "#line2"

text <- "line1
line2"

text <- "

# hello


this is new #hello
"

function() {
    1
# }
    2
}

```

### CODE REVIEW

**Comment by Ikuyadeu** [comment]
@renkun-ken Thank you.
`removecommentedlines` looks be unused.
Could you remove this or rewrite that function to use `trim`.

**Comment by renkun-ken** [comment]
I'd prefer removing `removeCommentedLines`, and then `checkForBlankOrComment` is not used either. Should I remove both?

**Comment by Ikuyadeu** [comment]
Yes, I agree with you.

**Comment by Ikuyadeu** [comment]
OK, looks good.

**Pull request merged**
