### PR TITLE
Session watcher options

### LINKED ISSUE #166: utils::browseURL
In the latest version of the R extension with `r.sessionWatcher": true` trying to open an external URL create a new tab in VSCode for a webview but the screen remains black. 

```
utils::browseURL("https://gitlab.com/")
```

### LINKED ISSUE #243: How do you open webview in new window automatically?
Is there a way to open help files via the `webview` functionality in a new window? At the moment, it seems to open in the same window where I executed the code?

Is this possible? If not, could this be a an option?

### LINKED ISSUE #277: Disable show plot
Hello, first of all, thank you very much for developing this wonderful extension.

Question: Is there any way to disable the display of the plot in the second vscode editor?

I'm asking because I prefer to view the graphs in an external editor.

Goodbye and thank you. 

PD: Sorry I made a mistake, I should have tagged it as a feature request, now I can't change it.

### LINKED ISSUE #331: Suggestion: allow plots from session watcher to share editing pane
@renkun-ken pointed me to the fact that session watcher allows you to see plots from a remote session natively in VSCode. This is amazing, and I wasn't aware of it until now.

Just one suggestion though: the watcher displays plots by splitting the editing pane vertically. When you also have your panes arranged vertically, this messes up the layout -- see screenshot below.

image

Is it possible to change the default layout for the session watcher, so that it shares the pane with the existing contents? I'd like to be able to arrange things so that it looks like this.

image

Dragging and dropping the pane works, but it goes back to the default layout as soon as I make a new plot.

### PR DESCRIPTION
**Pull request by renkun-ken**
This PR addresses #358 and contains a major rewriting of `init.R` with several options added to customize the functionality of session watcher and it also makes it easier for user to call viewer functions.

## New options

* Plot created by plot functions:
  * [x] `options(vsc.plot = FALSE)` to disable session watcher plot device (Close #277)
  * [x] `options(vsc.plot = "Active" | "Besides" | "Two")` to customize plot [ViewColumn](https://code.visualstudio.com/api/references/vscode-api#ViewColumn) (Close #331)
  * [x] `options(vsc.dev.args = list(width = 800, height = 600))` (previously unannounced `options(dev.args)`) to customize session watcher png device arguments. 
* `browser` webview created by shiny, R help, httpgd, etc.
  * [x] `options(vsc.browser = FALSE)` to browse URL in external web browser
  * [x] `options(vsc.browser = "Active" | "Besides" | ...)`  to customize browser WebView [ViewColumn](https://code.visualstudio.com/api/references/vscode-api#ViewColumn): https://github.com/Ikuyadeu/vscode-R/issues/329#issuecomment-641004693 (Close #243, Close #166)
* `viewer` and `page_viewer` webview created by htmlwidgets, profvis, etc.
  * [x] `options(vsc.viewer = FALSE)` to show viewer page (e.g. shiny app) in external web browser
  * [x] `options(vsc.page_viewer = FALSE)` to show page viewer page (e.g. profvis) in external web browser
  * [x] `options(vsc.viewer = "Active" | "Besides" | ...)` and `options(vsc.page_viewer = "Active" | "Besides" | ...)` to customize the ViewColumn of viewer and page_viewer (Close #243)
* Data webview created by `View()`
  * [x] `options(vsc.view = "Active" | "Besides" | ...)` to customize ViewColumn of `View` (Close #243)

## Public functions

This PR also attaches `tools:vscode` to make public the following functions in user search path instead of putting everything in an option (`getOption("vscodeR")`):

* `.vsc.attach()`
* `.vsc.view(..., viewer)`
* `.vsc.browser(url, title, ..., viewer)`
* `.vsc.viewer(url, title, ..., viewer)`
* `.vsc.page_viewer(url, title, ..., viewer)`

Now `r.attachActive` command sends `.vsc.attach()` to the terminal.

The viewer functions got an argument `viewer` to specify the ViewColumn to show the WebView or file or use external web browser. These viewer functions are also made to support the use cases like the following:

* Show htmlwidget with customized title and viewer position

```r
.vsc.viewer(DT::datatable(mtcars), "some data", viewer = "Beside")
```

* Render Rmarkdown document and show the HTML file in the viewer

```r
.vsc.viewer(rmarkdown::render("doc1.Rmd"))
```

We could make it a shortcut to render Rmd and view the output file, e.g.

```json
{
    "key": "ctrl+shift+r",
    "command": "r.runCommandWithEditorPath",
    "when": "editorTextFocus && editorLangId == 'rmd'",
    "args": ".vsc.viewer(rmarkdown::render(\"$$\", output_format = rmarkdown::html_document()))"
}
```

## Better support of customized plot device

With this PR, user could use, for example, the following code to customize session watcher behavior in `.Rprofile`:

For example, we could use [httpgd](https://github.com/nx10/httpgd) as the plot device (if installed) and opens a WebView to show the plot beside the active document when the device is created.

```r
if ("httpgd" %in% .packages(all.available = TRUE)) {
  options(vsc.plot = FALSE)
  options(device = function(...) {
    httpgd::httpgd()
    .vsc.browser(httpgd::httpgdURL(), viewer = "Beside")
  })
}
```

For advanced users who prefer self-managed sessions:

```r
if (interactive() && Sys.getenv("RSTUDIO") == "") {
  Sys.setenv(TERM_PROGRAM = "vscode")
  if ("httpgd" %in% .packages(all.available = TRUE)) {
    options(vsc.plot = FALSE)
    options(device = function(...) {
      httpgd::httpgd()
      .vsc.browser(httpgd::httpgdURL(), viewer = "Beside")
    })
  }  
  source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))
}
```

Kapture 2020-06-12 at 22 42 17

To recover the closed plot view, we could add the following shortcut:

```json
{
        "key": "ctrl+alt+p",
        "command": "r.runCommand",
        "when": "editorTextFocus && editorLangId == 'r'",
        "args": ".vsc.browser(httpgd::httpgdURL(), viewer = \"Beside\")"
}
```

## Other changes

The modification of `.Platform` is removed since when `.Platform$GUI` is modified, `options(vsc.plot = FALSE)` will fallback to `pdf` devices rather than X11 plot window on Linux and macOS.

## For existing persistent R sessions

If the extension is upgraded and user needs to work with existing self-managed, persistent R sessions, user has to manually source `init.R` before attaching.

### CODE REVIEW

**Comment by Ikuyadeu** [comment]
Thank you for much functional work.

It's been improved by many of your recent contributions, but I'm writing a new PR to make the code more maintainable.

**Comment by renkun-ken** [comment]
Thanks very much for your review! Your improvement of code is already appreciated!

**Comment by renkun-ken** [comment]
Also in the changelog of next release, would you mind adding the following for users who upgrade the extension but tries to work with existing R session which still sourced the old `init.R`:

```
To work with existing self-managed, persistent R sessions as the extension is upgraded,
source the `init.R` again before attaching.
```

```r
source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))
```

**Comment by pholck** [comment]
Noob here, but wondering if this functionality can be used to pipe a function's html output directly to an external browser (like Hmisc::html(), which generates HTML as output and displays nicely in RStudio). Likely I'm missing something and that ability already exists?  Thanks

**Comment by renkun-ken** [comment]
@pholck Do you mean previewing user generated html in a viewer tab? When sesssion watcher is enabled, the following code will open a viewer:

```r
html <- htmltools::HTML("<b>hello</b>")
htmltools::html_print(html)
```

**Comment by pholck** [comment]
@renkun-ken Of course. Very simple. Thank you very much.

**Pull request merged**
