### PR TITLE
WIP Migrate to vscode-test #315

### LINKED ISSUE #315: Migrate tests to vscode-test
Unit tests seem to have stopped working, I think since VS Code's switch to `vscode-test` for extension tests.

Migration guide: https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

### PR DESCRIPTION
**Pull request by andycraig**
Closes #315 

**What problem did you solve?**

Unit tests were not working. This PR migrates unit tests to `vscode-test`. Now unit tests work again.

**How can I check this pull request?**

1. Run -> Start Debugging...
1. Select 'Launch Tests' from the dropdown
1. Press <kbd>F5</kbd>
1. Observe Debug Console shows output ending with

```
    ✓ Selecting multi-line bracket with pipe    spec.js:76
    ✓ Selecting shorter RStudio comparison      spec.js:76
  22 passing (164ms)
```

### CODE REVIEW

**Comment by renkun-ken** [comment]
I tried running the test but the following error occurs:

```
Error: Error: Cannot find module '/Users/ken/Workspaces/github/vscode-R/out/test/suite/index'
Require stack:
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at h._doHandleExtensionTests (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:827:661)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
HttpError: request to https://api.github.com/user failed, reason: connect ECONNREFUSED 13.250.168.23:443
	at /Users/ken/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:1113
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
HttpError: request to https://api.github.com/gists/8398cc2babf3042d1ede4cb33524d4f1 failed, reason: connect ECONNREFUSED 13.250.168.23:443
	at /Users/ken/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:761:1113
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by andycraig** [comment]
@renkun-ken Thanks for testing! That's similar to an error I was getting earlier but I thought I'd fixed. Can you check if the following files exist? (Note they are JavaScript `.js` files.)

- `/Users/ken/Workspaces/github/vscode-R/out/test/suite/index.js`
- `/Users/ken/Workspaces/github/vscode-R/out/test/runTest.js`

**Comment by andycraig** [comment]
Actually I'm getting the same error after removing my `out` directory. I had evidently created that with some earlier operation.

**Comment by andycraig** [comment]
I'm making several changes so I'm going to close this PR and open a new one.

**Pull request closed without merging**
