### PR TITLE
RMarkdown knit support

### LINKED ISSUE #121: Add a command to knit the current Rmd file
**Is your feature request related to a problem? Please describe.**
I find it frustrating to have to continually jump to the R window and type `rmarkdown::render("filename.Rmd") when developing an R markdown file.

**Describe the solution you'd like**
A command that works like `runSource`, except it knits the current file.

I don't know anything about developing VS code plugins, but here's a stab at a function that might work? I just copied `runSource`, changed `source` and removed `setFocus`.

```ts
    function knitSource(echo: boolean)  {
        const wad = window.activeTextEditor.document;
        wad.save();
        let rPath = ToRStringLiteral(wad.fileName, '"');
        let encodingParam = config.get("source.encoding") as string;
        if (encodingParam) {
            encodingParam = `encoding = "${encodingParam}"`;
            rPath = [rPath, encodingParam].join(", ");
        }
        if (echo) {
            rPath = [rPath, "echo = TRUE"].join(", ");
        }
        if (!rTerm) {
            const success = createRTerm(true);
            if (!success) { return; }
        }
        rTerm.sendText(`rmarkdown::render(${rPath})`);
    }
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by dominicwhite**
**What problem did you solve?**

Fixes #121 

I'd independently had a the same issue as @a-torgovitsky in Issue #121  - needing a shortcut to knit RMarkdown files.

@mattva01 and I added commands to knit based on @a-torgovitsky's code snippet in his issue. Specifically:

* One command that Knits to the default document type (i.e. the first type specified in the Rmd header section). Shortcut Ctrl + Shft + K is the same as RStudio.
* One command that Knits specifically to PDF.

**Screenshot**

An open Rmd file now looks like:

Screenshot_20190911_211904

However, we are currently reusing the "Run Source" icon for both Knit options (default and PDF):

Screenshot_20190911_211950

I tried creating a custom icon, but the text was far to small to be functionally useful, so I'm not sure what the best solution to this is (perhaps just a single Run Source icon, which runs the default Knit command? Or is reusing the Run Source icon too confusing).

**Additional commands (that I would like, at least)**

* Add a Knit to HTML command (which would be useful for my students).
* Add a Knit to All command.

### CODE REVIEW

**Comment by dominicwhite** [comment]
@andycraig @Ikuyadeu Thanks for the suggestions.

I just added two extra commands, to Knit to HTML and All formats.

I will look into the icons you suggested later today, and try to get the pull request ready to by merged.

**Comment by dominicwhite** [comment]
@andycraig @Ikuyadeu I have removed the WIP tag, so please review and let me know if you would like any changes.

Regarding icons: In the end I left a single Run Source icon in place, which reruns the basic Knit command (to the default output type). The other three Knit options are available as commands, but I could not find 4 appropriate icons in the Visual Studio collections.

**Comment by Ikuyadeu** [comment]
@dominicwhite Thank you for a good fix.
I will check this PR on Monday.

**Comment by Ikuyadeu** [comment]
@dominicwhite Sorry, my reply is late. I checked this now.

**Pull request merged**
