### PR TITLE
add syntax highlight for DESCRIPTION and .Rproj

### PR DESCRIPTION
**Pull request by qinwf**
**What problem did you solve?**

add syntax highlight for DESCRIPTION and .Rproj

There files are [Debian Control File](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file)

**(If you have)Screenshot**

desc

### CODE REVIEW

**Comment by renkun-ken** [comment]
Thanks for the nice work! This works as expected.

@andycraig Do you think if there's anything to be added?

**Comment by andycraig** [comment]
@gowerc Thank you for this. I didn’t know they were Debian Control Files!

@renkun-ken Thank you for checking. I don’t think anything else is needed.

**Comment by andycraig** [comment]
@qinwf @gowerc Apologies to you both, I got the PR authors mixed up!

**Comment by qinwf** [comment]
Thank you.

**Pull request merged**
