### PR TITLE
Extend View

### LINKED ISSUE #51: Support for displaying plots and help files in VS Code IDE
Great work on this, thank you!

One thing I find useful is to see plots and help documents in the IDE (both RStudio and R Tools for Visual Studio offer this). It would be great to have the same thing for R in VS Code.

The [julia-vscode](https://github.com/JuliaEditorSupport/julia-vscode) and [pythonVSCode](https://github.com/DonJayamanne/pythonVSCode) extensions both include plot panes within VS Code itself, which I guess means it's possible.

Thanks

### LINKED ISSUE #160: Support View environment
With existing `View(data.frame)` supported, it is easy to support `View(environment)` as a simple environment viewer to make it easy to inspect the global environment using `View(globalenv())`.

image

### LINKED ISSUE #162: Support View function
`View()` can be extended to support function input. A document can be open to show the function body.

### LINKED ISSUE #175: Use FixedHeader in View(data.frame)
Use FixedHeader extension of DataTables to make header persistent while scrolling.

See https://datatables.net/extensions/fixedheader.

### PR DESCRIPTION
**Pull request by renkun-ken**
**What problem did you solve?**

Closes #160 
Closes #162 
Closes #51 
Closes #175 

**Screenshot**

```r
View(globalenv())
```

image

```r
View(lm)
```

image

```r
View(rnorm(100))
```

image

```r
m <- summary(lm(mpg ~ ., data = mtcars))
View(m)
```

image

```r
?rnorm
```

image

Use FixedHeader in `View(data.frame)`

image

### CODE REVIEW

**Comment by vnijs** [comment]
This is **really** nice! 

Question: Is there a reason why init.R is put into ~/.vscode-R/ and not into ~/.vscode/vscode-R/ ?

**Comment by vnijs** [comment]
Related to View (and shiny apps) in VSCode, if you go another tab (i.e., the WebView is hidden), state information is lost. As an example, open help for `?rnorm`, scroll down, switch to another tab, and then back to the WebView. You will see it "reopen" the page and the information about where you were on the page is lot.

I think this could be resolved by setting `retainContextWhenHidden` (see links below). 

https://code.visualstudio.com/api/extension-guides/webview#retaincontextwhenhidden
https://code.visualstudio.com/api/extension-guides/webview#getstate-and-setstate

Recent issue that mentions window.localStorage:

https://github.com/microsoft/vscode/issues/82597#issuecomment-545783814

**Comment by renkun-ken** [comment]
@vnijs Yes, now all WebViews are open with `retainContextWhenHidden` turned on.

**Comment by renkun-ken** [comment]
> Question: Is there a reason why init.R is put into ~/.vscode-R/ and not into ~/.vscode/vscode-R/ ?

No specific reason for that. If `~/.vscode/vscode-R` looks nicer and is typical for vscode extensions to store file on user machine, we may switch to it too. The only difference at the moment is that it is shorter.

**Comment by vnijs** [comment]
I'm not sure what is typical but it seems like a good idea to try and limit the number of dot files. There are so many in my home directory already :-)

**Comment by iainmstott** [comment]
This works really well for me! Great work. Really like the addition of the hover and View() functionality. Awesome!

One thing I'd note is that for whatever reason, I did need to restart VSCode twice to get it working. Don't know why. After the first restart, nothing happened after running the commands. But now it's working exactly as expected.

**Comment by renkun-ken** [comment]
@Ikuyadeu @andycraig This PR is ready for merge. Please take a look.

**Comment by andycraig** [comment]
@renkun-ken @Ikuyadeu This is great! It all works fine for me on Windows 10.

**Comment by Ikuyadeu** [comment]
@renkun-ken Thank you for the pull request.
@andycraig Thank you for reviewing.

**Pull request merged**
