### PR TITLE
Refactoring and implementation of webviewPanelSerializer

### PR DESCRIPTION
**Pull request by ManuelHentschel**
**What problem did you solve?**
This PR mostly contains refactoring/cleanup of help related files.
The only change to the extension's behaviour is the implementation of `rHelp.deserializeWebviewPanel`

https://github.com/Ikuyadeu/vscode-R/blob/c4c6334798b694185619f85d321fd92e1880fa39/src/rHelp.ts#L180-L184

implementing `vscode.WebviewPanelSerializer`.

**How can I check this pull request?**
Open some help pages and reload/restart vscode, check if the help pages are still open

### CODE REVIEW

**Comment by renkun-ken** [comment]
If a single Help Page is open, it will recover after reloading.

If multiple Help Pages are open, only the last one will recover and others are blank. Do you think we need to handle this so that all help pages could be recovered?

**Comment by ManuelHentschel** [comment]
> If multiple Help Pages are open, only the last one will recover and others are blank. Do you think we need to handle this so that all help pages could be recovered?

Thanks for catching that! Should be fixed now

**Comment by renkun-ken** [comment]
Thanks! It works properly with multiple help tabs now.

**Review by renkun-ken — APPROVED** [review]
LGTM

**Pull request merged**
