### PR TITLE
Added Dataviewer Command

### PR DESCRIPTION
**Pull request by Ladvien**
I've added a command which captures what is selected as the name of the dataframe, passes it to the RTerm to write as a CSV, polls the file size of the CSV to assure it is completely written, then opens the CSV, lastly, it uses the Excel Viewer csv.preview command to view the dataframe inside vscode.

There is a limitation of nothing larger than 5 MB dataframes due to vscode issue:

https://github.com/Microsoft/vscode/issues/32118

But this look it will be resolved during the next update.  Currently, the Preview Dataframe command gracefully fails if dataframe exceeds 5 MB's, notifying the user of the limitation.

### CODE REVIEW

**Comment by Ikuyadeu** [comment]
@Ladvien Thank you PR.
Looks good! But I can't review this week, sorry.
Please wait until next week.

**Comment by Ladvien** [comment]
Ok, no worries.

**Comment by Ikuyadeu** [comment]
@Ladvien Please delete .DS_Store or add this file in .gitignore.

**Comment by Ladvien** [comment]
Done.

**Comment by Ikuyadeu** [comment]
Thank you @Ladvien!
Your submit is good always.
I want to send commit authority to you. How do you think?

**Comment by Ladvien** [comment]
Thank you! That'd be great--if you OK with it?

**Pull request merged**
