### PR TITLE
Prerelease version 1.6.4

### PR DESCRIPTION
**Pull request by Ikuyadeu**
**What problem did you solve?**

I put the prerelease version of 1.6.4

**(If you do not have screenshot) How can I check this pull request?**

If this change has problem, please notice to me.

### CODE REVIEW

**Comment by Ikuyadeu** [comment]
This PR was the test for the auto vsce release.

**Comment by Ikuyadeu** [comment]
Auto releases may work on the direct commit, but the current latest tag will make the error for that.

**Comment by Ikuyadeu** [comment]
> git pull --tags origin master
From https://github.com/Ikuyadeu/vscode-R
 * branch            master     -> FETCH_HEAD
 ! [rejected]        latest     -> latest  (would clobber existing tag)

**Comment by ManuelHentschel** [comment]
Hi @Ikuyadeu, sorry for the late reaction, I didn't notice this PR earlier.

To trigger the auto vsce release, you need to create and push a tag called `v1.6.4`. To achieve this, I used the following commands:
```
> git tag v1.6.4 75ef250130a7c76e45b4817a0b996e937c940e24
> git push origin v1.6.4
```
The commit hash (`75ef25...`) can be omitted if you want to tag the commit that is currently checked out.

The GitHub release worked as expected (found [here](https://github.com/Ikuyadeu/vscode-R/releases/tag/v1.6.4)), the vsce auto publish failed because there already was a v1.6.4, but seems to have worked otherwise.

**Comment by ManuelHentschel** [comment]
> branch master -> FETCH_HEAD
> ! [rejected] latest -> latest (would clobber existing tag)



Regarding the `latest` tag I wouldn't worry too much. This tag gets updated automatically each time something is pushed/merged to the master branch and is only used to (pre-)release the [development build](https://github.com/Ikuyadeu/vscode-R/releases/tag/latest).

**Comment by Ikuyadeu** [comment]
@ManuelHentschel Thank you for your response.
OK, I'll be careful that things.

**Pull request merged**
