### PR TITLE
Fix typo in help panel path config

### PR DESCRIPTION
**Pull request by ManuelHentschel**
#454 #455
Fix typo in accessing config entry `r.helpPanel.rpath` which caused this setting to be ignored.

### CODE REVIEW

**Comment by renkun-ken** [comment]
Thanks for the fix! It looks like `r.helpPanel.rpath` does not default to `r.rterm.*` but `getRpath()`, which is inconsistent with the description

>Defaults to `r.rterm.XXX`.

Could you confirm that and update the description if it is the case?

**Comment by ManuelHentschel** [comment]
> 
> 
> Thanks for the fix! It looks like `r.helpPanel.rpath` does not default to `r.rterm.*` but `getRpath()`, which is inconsistent with the description
> 
> > Defaults to `r.rterm.XXX`.
> 
> Could you confirm that and update the description if it is the case?

I used that description, since `getRpath()` will read the corresponding `r.rterm.xxx` setting first and only be different from accessing the setting directly if it needs to fall back to a different  method

**Comment by ManuelHentschel** [comment]
But I'd suggest skipping the `r.rterm.xxx` fallback and instead use the fallback methods used in `getRpath()` directly

**Comment by renkun-ken** [comment]
Yes, that's exactly what I meant. Forgot that getRpath reads config first.

**Review by renkun-ken — APPROVED** [review]
LGTM

Tested on macOS and it works nicely now.

**Pull request merged**
