### PR TITLE
Use fs.watch instead of vscode.FileSystemWatcher

### LINKED ISSUE #179: Unable to attach terminal with Google Drive (Drive File Stream)
I am using Windows 10 OS, and when I tried to use the session watcher, the R terminal cannot be attached. (neither auto attach or manually `getOption('vscodeR')$attach()`)

I observed `response.log` was changing over time (as below), but obviously there was no attached R session or any expected window pop-up for dataview.

```

{"time":"2020-01-08 18:10:23","pid":7220,"command":"attach"} 
{"time":"2020-01-08 18:10:26","pid":7220,"command":"attach"} 
{"time":"2020-01-08 18:10:44","pid":7220,"command":"dataview","source":"table","type":"json","title":"mtcars","file":"C:\\Users\\kooho\\AppData\\Local\\Temp\\RtmpOKdp0S\\file1c3430431451.json"} 
{"time":"2020-01-08 18:10:49","pid":7220,"command":"attach"} 
{"time":"2020-01-08 18:15:47","pid":3172,"command":"attach"} 
{"time":"2020-01-08 18:19:31","pid":5868,"command":"attach"} 
{"time":"2020-01-08 18:19:34","pid":5868,"command":"attach"} 
```

### LINKED ISSUE #236: Session watcher only working in the first attached VScode folder
**Describe the bug**
In a VScode workspace I am only able get the R session watcher working in the first attached folder.

**To Reproduce**
1. Create the following folder structure
image

1. Attach folders in VScode (`File>Add Folder to Workspace...`) to obtain the following: 
image

1. In the setup above start an R terminal under `project_1`. The R session ID should be properly shown in the VScode status bar

1. Now do the same but start a new R terminal under `project_2` instead. The VScode status bar will stay with `R: (not attached)`

_Note: if the `project_2` folder were attached first to VScode (i.e. shown first in the side bar list) then the Rsession watcher would work for `project_2` but not for `project_1`_.

`setting.json`
```json
    "r.alwaysUseActiveTerminal": true,
    "r.bracketedPaste": true,
    "r.rterm.mac": "/usr/local/bin/radian"
    "r.sessionWatcher": true
```

**Expected behavior**
R session watcher should be able to work no matter from which folder it has been attached.

**Environment:**
 - OS: macOS
 - VSCode Version: 1.42.1
 - R Version: 3.6.2
 - vscode-R version: 1.2.3

**Additional info**
This could be an extension of #196

### LINKED ISSUE #272: Session Watcher does not show graphs
**Describe the bug**

After enabling the session watcher I do not get the pane showing the graphs (nor am I getting a quartz windows). I do see a png for the graph stored in the PID folder within the .vscode/vscod-R folder though. So the problem seem to stem from the pane not opening.
I tried installing radian to see if that would help and got a separate issue, which I'll report in another thread.

**Do you want to fix by self? (I hope your help!)**

Yes

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

Maybe some guidance as to what I could try to fix...

(If related)setting.json

   "r.sessionWatcher": true,
    "r.bracketedPaste": true,
    "r.rterm.option": [],
    "r.alwaysUseActiveTerminal": true,
    "r.lsp.path": "/usr/local/bin/R"

**Expected behavior**
Some guidance to fix that issue!
**Environment (please complete the following information):**
 - OS: [e.g. Windows, macOS, Linux]
OSX mojave 10.14.6

 - VSCode Version: [e.g. 1.42.0]
1.43.2

 - R Version: [e.g. 3.6.2]
3.6.1 (2019-07-05) -- "Action of the Toes"
Installed from CRAN distribution

 - vscode-R version: [e.g. 1.2.2]
1.2.7

Many thanks for your help

### LINKED ISSUE #330: Every time R terminal opens in VS Code , getting below...any idea how to fix?
[1] FALSE
> C:/Users/.../AppData/Local/Continuum/miniconda3/Scripts/activate
Error: unexpected '/' in "C:/"
> conda activate base
Error: unexpected symbol in "conda activate"

### LINKED ISSUE #347: Move to fs.watch in session watcher
Currently, session watcher uses `vscode.FileSystemWatcher` to watch `response.log`, session `globalenv.json`, `plot.png` files. However,`vscode.FileSystemWatcher` is limited to only work for a glob pattern in workspace folders, which makes it necessary for `init.R` to create these files in workspace folder.

If the workspace folder is a git repo, then it is annoying that user always has to ignore `.vscode/vscode-R` folder.

I just notice that we don't really need `vscode.FileSystemWatcher` to watch a glob pattern in workspace but need to watch specific file with known paths. In this case, if we use [`fs.watch`](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) or [`fs.WatchFile`](https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener) instead, we don't have to create these session files inside the workspace folder, then no need to git-ignore them.

We could then use a central place to place the `response.log` (e.g. `~/.vscode-R/response.log`) and session temp dir to store `globalenv.json` and `plot.png`. To attach a session, the temp dir of that session is written to `response.log` so that session watcher knows the exact path of `globalenv.json` and `plot.png` to watch.

This will make it possible to work in workspace folders in cloud-based folders since we no longer have to watch files in cloud folders, which is not supported (#179, #272, #297)

### LINKED ISSUE #352: too many R sessions left at R-project folder under .vscode
when create a new terminal, vscode-r will not pick up the previous r-session files. and the old files under previous session id are kept and will have more and more session files. Should the extension delete those old session files or reusing the files? every time when a new terminal is created, a new session folder is created, it goes ugly.

### PR DESCRIPTION
**Pull request by renkun-ken**
* Close #347
* Close #352 
* Support multi-root workspace (Close #236)
* Support workspace in cloud drive (Close #179, Close #272, Close #330) and read-only file systems

This PR uses `fs.watch` to replace `vscode.FileSystemWatcher` and the `response.log` renamed to `request.log` and is moved to `~/.vscode-R/request.log`; `globalenv.json` and `plot.png` are moved to `{tempdir}/vscode-R/`.

Note that `fs.watch` may trigger multiple events when the watched file is being written. If we directly watch `request.log`, `globalenv.json`, and `plot.png`, respectively, it is likely that we might read a partial file that is still being written. To avoid this, I use lock files for each of them, i.e., `resquest.lock`, `globalenv.lock`, `plot.lock`. In `init.R`, these lock files are written a timestamp after the underlying file is finished writing. Only when the file watch triggers an event and the timestamp changes do we read or open the underlying file to avoid duplicate reading or partial reading.

All functionalities of session watcher should not change. The only visible change is that it no longer creates `{workspaceFolder}/.vscode/vscode-R`.

**Testing this PR**

* General functionalities
  - attach
  - symbol hover
  - `View(mtcars)`
  - `View(baseenv())`
  - `plot(rnorm(100))`
  - R session started from a subfolder of the VSCode workspace root should work now.
* Multi-session support
  - Open a workspace at folder A
  - Create multiple terminals
  - Each should be able to attach
  - Click status bar in previously created terminal and it should attach
  - In the attached session, `plot(rnorm(100))` should open the png file
  - In any of the sessions, `View(mtcars)` should trigger the WebView
* Multi-root workspace support
  - Create a multi-root workspace
  - Start an R session from one workspace folder should work
  - Start an R session from the second workspace folder should work too
* Cloud-drive support
  - Create a workspace in a cloud-drive (e.g. OneDrive, Google Drive)
  - Start an R session from the workspace folder
  - The session watcher should work normally
* Read-only file system support
  - Open a workspace in a read-only file system (e.g. a read-only mounted drive, or non-writable directory for our user)
  - Start an R session from the workspace folder
  - The session watcher should work normally

### CODE REVIEW

**Comment by renkun-ken** [comment]
Now the `response.log` file is located at `~/.vscode-R`, then if multiple VSCode is running with different workspace folders, then a new R session will make all VSCode attach the newly created R session, which is certainly not desired. Let me think about this more.

It seems we should also add the working directory to the attach info so that the responseWatcher only handles the attach command by session whose working directory is a subfolder of any of the workspace folders.

**Comment by renkun-ken** [comment]
The file watcher now watches `request.lock`, `globalenv.lock`, and `plot.lock` to avoid reading partially written file if the data being written is large. And `request.log` no longer keeps history so that we don't have to scan to the last line to get the command line.

**Comment by andycraig** [comment]
@renkun-ken I tried this on Windows 10 just now. I used a directory containing an empty file `temp.R` and `.Rprofile` with contents copied from the README.

When I use `R: Create R terminal` I get the following error:

```
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'C:\Users\AC\Documents\.vscode-R/request.log': No such file or directory
```

Looking in `C:\Users\AC\Documents\`, there is no directory `.vscode-R`.

When using `master` this error doesn't occur.

**Comment by renkun-ken** [comment]
@andycraig Thanks for testing on Windows. It looks like `deploySessionWatcher()` does not run at all? Would you like to post the extension logging?

**Comment by renkun-ken** [comment]
@andycraig I could reproduce it on my Windows 10 VM. Let me take a closer look at this.

**Comment by renkun-ken** [comment]
@andycraig Fixed on Windows. I've tested on macOS, Ubuntu and Windows and everything looks good now.

**Comment by andycraig** [comment]
@renkun-ken Thanks for fixing! Everything else works now for me in Windows 10, except cloud-drive support which I didn't try.

I had a look at the changes but there are so many that I'm not realistically going to be able to do a proper code review. You've done a lot of work on this, thank you! When I tested everything worked so I'm happy for this to be merged without code review. @Ikuyadeu Okay to merge this without code review?

**Comment by renkun-ken** [comment]
@andycraig  Thanks for testing! The code diff is actually so so much since most diff lines in `init.R` are only indention changes.

The cloud drive support should be automatically working since we don't watch any files in user workspace folder now. Session watcher should now work for any file system that user could open a workspace.

**Comment by renkun-ken** [comment]
Thanks for the testing! I've been using this in my work for quite a while and everything looks good.

**Comment by renkun-ken** [comment]
Here's a note for users who works with user-started R sessions. Since the watch files changed, the old R sessions will not work directly when attached. User has to explicitly source the latest `init.R` script before attach to make session watcher work.

**Pull request merged**
