### PR TITLE
Add function to open help for selected text

### LINKED ISSUE #528: Add context menu item to show help for word at cursor
Now we have `R: Show Help` command and a help viewer pane. It would be nice if we also add a context menu item so that user could right click on a symbol and show help directly.

### PR DESCRIPTION
**Pull request by ManuelHentschel**
**What problem did you solve?**
Fix #528 
This PR adds a command `r.helpPanel.openForSelection` that opens the help page for the currently selected function/topic.
Does not contain any error notifications if no matching help page is found.
Does not contain automatic detection of the correct "token" to be used.
Does not containt automatic detection of the correct package to be used (if not specified by using `::`).

**How can I check this pull request?**
Type e.g. `print`, `base::print`, `base:::print`, select the text and execute the command `r.helpPanel.openForSelection`.

### CODE REVIEW

**Comment by renkun-ken** [comment]
I did some editing with the following updates:

1. Use the word at cursor if selection is empty
2. Add command to r/rmd editor context menu.

I think this PR is good enough for typical use already.

**Review by renkun-ken — APPROVED** [review]
LGTM

**Comment by ManuelHentschel** [comment]
The last two commits add:
* Error notifications no help page is found/no text selected
* New regex to use the specified package e.g. in `base::print`
* Command in the help tree view

**Comment by renkun-ken** [comment]
@ManuelHentschel  Would you like to resolve the conflicts before merging?

**Pull request merged**
