### PR TITLE
Inject R Markdown features into Markdown grammar

### LINKED ISSUE #36: RMarkdown citations not highlighted properly in R Markdown syntax format
- VSCode Version: 1.18.1
- VSCode-R Version: 0.5.0
- OS Version: macOS 10.13.1

Steps to Reproduce:

1. Edit an `.Rmd` document with citations in it.
2. Ensure that `R Markdown` is selected as the highlighting language.

screenshot 2017-11-20 12 33 58

In this case, the citations aren't recognised by the highlighting, and pairs of underscores are read as italicisation. If the citation key has an odd number of underscores, the italicisation continues past the citation on to the next underscore.

### LINKED ISSUE #48: better language highlight for Rmd
The current support for R markdown language highlight is awesome. While I think the following aspects are overweighted by VScode's native markdown support.

highlight for Rmd
image

highlight for md
image

```md
1. item

- item

+ item

* item

> Blockquotes

`inline code`
```

### LINKED ISSUE #116: Line breaks in markdown break highlight
**Describe the bug**
Using line breaks in markdown `***` will break syntax highlighting on Rmd files

**To Reproduce**
Have an Rmd file:

`````
# this is a test

```{r test1}
# syntax highlighting works fine here
library(iris)
head(iris)
```

below is a line break

***

```{r test2}
# syntax highlighting no longer works
library(iris)
head(iris)
```

## even the markdown highlighting breaks

***

```{r test3}
# syntax highlighting works again
library(iris)
head(iris)
```

## highlighting works again

`````

**Do you want to fix by self? (I hope your help!)**

No :(

**Expected behavior**
Syntax highlighting work between line breaks

**Environment (please complete the following information):**
 - OS: OSX
 - VSCode Version: 1.35
 - R Version: 3.5.1
- Plugin version: 1.1.1

### LINKED ISSUE #220: Line Comment in Rmarkdown
In an Rmd file, outside of code chunks, using the 'Toggle Line Comment' command should add an HTML comment, not a `#`

Commenting out `TEXT` should result in
```
<!-- TEXT -->
```
and not
```
# TEXT
```

### PR DESCRIPTION
**Pull request by andycraig**
Closes #220 (HTML comments)

Closes #116 (linebreaks)

Closes #48 (block content in lists)

Closes #36 (citations, list items, YAML frontmatter)

**What problem did you solve?**

VSCode provides a Markdown grammar, but it was being overruled by our R Markdown grammar. This PR uses the Markdown grammar, and injects just the necessary R Markdown features (chunks with `{r}` etc., inline R code).

**Screenshots**

Before:

example1_before

After:

example1_after

**How can I test this pull request?**

1. Create an Rmd file with this text (removing leading spaces if necessary):

```
    ---
    title: YAML header
    ---

    # Inline R

    `r x <- 1`

    # R Markdown R block

    ```{r}
    head(iris)
    ```

    # C++ block

    ```{cpp}
    int x = 0;
    ```
```

2. Place cursor on line 1. Use `Edit -> Toggle Line Comment`. Verify that comment is HTML comment `<!-- -->`
2. Place cursor in R block. Use `Edit -> Toggle Line Comment`. Verify that comment is R comment `#`
2. Place cursor in C++ block. Use `Edit -> Toggle Line Comment`. Verify that comment is C++ comment `//`

Previously, all these comments were R style `#`.

### CODE REVIEW

**Comment by andycraig** [comment]
@Ikuyadeu @renkun-ken This works for me on Windows 10, but on Ubuntu the injection isn't working and Rmd files are being handled as Markdown files (no highlighting in `{r}` blocks, comments are always HTML comments). But, in the past I've had some odd highlighting issues on this PC. 

Could try the 'How can I test this pull request?' section and let me know if it works for you? If it does work for you, we can probably assume the source of my Ubuntu problem is my weird PC. If it doesn't work for you, my Ubuntu problem is probably genuine.

**Comment by renkun-ken** [comment]
This works for me on both macOS and Ubuntu.

However, the language server does not start on Rmd file. I'm not sure where should we change so that langauge server also starts with Rmd file.

**Comment by renkun-ken** [comment]
Looks like we should also update `activationEvents` of vscode-r-lsp.

**Comment by andycraig** [comment]
@renkun-ken Thank you for checking that for me. That’s good to hear. It sounds like the problem is specific to my PC, and the PR is probably fine.

Well noticed on the Rmd language server activation issue!

**Comment by renkun-ken** [comment]
Now vscode-r-lsp is also activated `onLanguage:rmd` via https://github.com/REditorSupport/vscode-r-lsp/pull/28. LTGM now.

**Comment by andycraig** [comment]
The R Markdown grammar still included many non-bracket code chunks, e.g.:

```
    ```ruby
```

These are already handled by the VSCode Markdown grammar, so I added a commit to remove them. The remaining chunks are:

```
    ```{r}
    ```{c}
    ```{cpp}
    ```{yaml}
```

This PR is ready to merge.

**Comment by atanasj** [comment]
Out of interest, will this also allow heading navigation as in `markdown` files?

**Comment by renkun-ken** [comment]
Now it works nicely as I tested.

**Comment by andycraig** [comment]
@renkun-ken Thank you for testing and approving. I will merge this PR now.

**Pull request merged**
