### PR TITLE
Migrate to vscode-test #315

### LINKED ISSUE #315: Migrate tests to vscode-test
Unit tests seem to have stopped working, I think since VS Code's switch to `vscode-test` for extension tests.

Migration guide: https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

### PR DESCRIPTION
**Pull request by andycraig**
Closes #315

**What problem did you solve?**

Unit tests were not working. This PR migrates unit tests to `vscode-test`. Now unit tests work again.

BUT, they only work from the command line. I could not get them to work from within VS Code. So, I have removed the 'Run Tests' option within VS Code for now. I would like to restore it at some point, but this PR at least gives us a way of running tests (which should also work in Continuous Integration).

**How can I check this pull request?**

In terminal, in `vscode-R` directory:

```
npm run test
```

The first time, it will take a while because it needs to download VS Code.

Eventually, observe output ending in:

```

    ✓ Selecting multi-line bracket with pipe
    ✓ Selecting shorter RStudio comparison

  22 passing (143ms)

Exit code:   0
Done
```

If this doesn't work, it may be necessary to run `npm install` first.

### CODE REVIEW

**Comment by andycraig** [comment]
`lintr` CI test is failing but during the installation phase. Maybe some package repo is offline. I will try running it again later.

**Comment by renkun-ken** [comment]
Thanks for the nice work! This works for me now.

I'm wondering if this only works under desktop environment?

Another thing is that it'll create a folder `.vscode-test` that is not ignored? Should we ignore this folder?

**Comment by andycraig** [comment]
Thanks for testing again! Good point about `.vscode-test` - I've added it to `.gitignore`.

> I'm wondering if this only works under desktop environment?

Do you mean, whether it would work in a container for CI? I think it would, although there would be some more dependencies.

**Comment by renkun-ken** [comment]
I make some changes to `main.yaml` for github actions according to https://github.com/renkun-ken/vscode-R/tree/migrate-vscode-test, and it works nicely now: https://github.com/renkun-ken/vscode-R/runs/658838903?check_suite_focus=true.

I'm not sure if there's a good way to incorporate my changes to `main.yaml`? Maybe I send a PR from my fork to your fork? Not sure about this.

**Comment by renkun-ken** [comment]
Just saw #318. I'll file a separate PR for this once this PR is merged.

**Comment by andycraig** [comment]
Nice! Looks like I created an issue just as you solved it :smile:

This PR is set to allow edits from maintainers, so you may be able to push directly to this branch. Or, doing a separate PR after is fine too.

**Comment by renkun-ken** [comment]
Just pushed to your branch and the tests look good.

LGTM now.

**Comment by andycraig** [comment]
Great! Thank you for adding the commits and reviewing.

The lintr installation is still failing but this PR doesn't change any R files anyway, so I'm going to go ahead and merge.

**Pull request merged**
