### PR TITLE
Send code to debug repl

### LINKED ISSUE #570: Send code to debug window
**Is your feature request related to a problem? Please describe.**
In a debugging session with https://github.com/ManuelHentschel/VSCode-R-Debugger, Ctrl + Enter still sends code to the R session.

**Describe the solution you'd like**
Ctrl + Enter sends to the debug window if `inDebugMode`.

**Describe alternatives you've considered**
I have mapped `editor.debug.action.selectionToRepl` to Ctrl + Enter if `inDebugMode` is set. This works but I need to select the code I want to send. I'd like to take advantage of this extension's ability to detect the R code to send to the debug window.

**Additional context**
Thanks for the great extension!

### PR DESCRIPTION
**Pull request by ManuelHentschel**
Fix #570 

Adds the possibility to send code directly to the debug console.

*How to check:*

* Launch a debug session using VSCode-R-Debugger
* In the .R file, press `ctrl+enter`
* Expected behaviour: text that is usually sent to the terminal is instead sent to the debug repl

This PR is WIP and needs some more fine tuning, but the basic functionality should be working.

### CODE REVIEW

**Comment by krlmlr** [comment]
Nice! What happens if the user already selected text? I'd expect that this (and only this) text is sent to the REPL.

**Comment by ManuelHentschel** [comment]
> Nice! What happens if the user already selected text? I'd expect that this (and only this) text is sent to the REPL.

The behaviour should be the same as with normal terminals, since I'm using the same background functions to select the text

**Comment by krlmlr** [comment]
Works for me, thanks!

**Review by renkun-ken — APPROVED** [review]
Works as expected. LGTM. Thanks!

**Pull request merged**
