### PR TITLE
WIP: Making the vscode-r original coding conventions

### PR DESCRIPTION
**Pull request by Ikuyadeu**
**What problem did you solve?**
Related with https://github.com/Ikuyadeu/vscode-R/issues/215 and https://github.com/microsoft/vscode/issues/94751

I added my linter devreplay to verify the vscode-specific problems, such as https://github.com/Ikuyadeu/vscode-R/pull/301

The deprecated functions are written on the `devreplay.json`

**(If you have)Screenshot**

I added bad syntax on the https://github.com/Ikuyadeu/vscode-R/compare/devreplay?expand=1#diff-f3fe9c4fe673e665c8df5914c3b9c9a0R333
After review, I will fix again that.

On the vscode:
May-05-2020 14-09-37

On the GitHub Action: https://github.com/Ikuyadeu/vscode-R/pull/308/checks

Screen Shot 2020-05-05 at 14 16 19

@andycraig @renkun-ken Could you check this?

### CODE REVIEW

**Comment by andycraig** [comment]
@Ikuyadeu Interesting! How should we check this?

**Comment by renkun-ken** [comment]
Looks quite interesting and useful. Is there anything we should do to check?

**Comment by Ikuyadeu** [comment]
@andycraig @renkun-ken  Thank you! I will merge this.
After merging this, you can get the lint result on vscode by installing [vscode-devreplay](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.devreplay)

**Comment by andycraig** [comment]
@Ikuyadeu Great! I’m looking forward to trying it.

**Pull request merged**
