### PR TITLE
fix lintr issue on windows

### LINKED ISSUE #34: Lintr does not work in Windows 10 when invoked from a folder with spaces
- VSCode Version: 1.18.0
- VSCode-R Version: 0.5.0
- OS Version: Windows 10 Pro 10.0.15063 Build 15063

Steps to Reproduce:

1. Install "R" on a folder with spaces ("C:\Program Files\R\R-3.4.2\bin\x64\R.exe")
2. Execute the command `R: lintr` from vscode

Related issues: 
 - https://github.com/nodejs/node/issues/7367
 - https://github.com/Ikuyadeu/vscode-R/issues/3

### PR DESCRIPTION
**Pull request by wedneyyuri**
Closes #34

### CODE REVIEW

**Comment by Ikuyadeu** [comment]
@wedneyyuri Thank you for PR. Looks good!
I'll review this in this weekend.

**Comment by Ikuyadeu** [comment]
@wedneyyuri Thank you!
I'll merge.

**Comment by Ikuyadeu** [comment]
@wedneyyuri Sorry this PR can't work my environment(Mac Sierra).
Once, I'll revert this and try after.

**Comment by wedneyyuri** [comment]
Ok, I'll try again this weekend.

**Pull request merged**
