### PR TITLE
Add updatePackage command

### PR DESCRIPTION
**Pull request by ManuelHentschel**
**What problem did you solve?**
#529 

**How can I check this pull request?**
This PR adds a command `Update/reinstall package` to the package tree view that reinstalls/updates the package. This is done by a simple call to `install.packages('PKG_NAME')` and does not check if the package is installed from CRAN and does not compare versions.

### CODE REVIEW

**Comment by renkun-ken** [comment]
Looks like the update button already works with single package.

I'm wondering if it makes sense to add similar to 

image

so that it is easier to update all installed packages by executing something like `update.packages(ask=FALSE)`?

**Comment by ManuelHentschel** [comment]
I added a command button to the entry `Install CRAN Package` (I felt it fits better there, since the other commands next to `Help topics by Package` only affect the tree view but don't install/modify any actual packages).

As you suggested, the command executes `update.packages(ask=FALSE, repos=<CRAN_URL>)`. On my machine this worked for most packages but some packages seem to cause problems. I think this is caused by them being loaded somewhere, so that their .DLL files cannot be overwritten. I don't think there is a simple solution for this, so I wouldn't try to fix this, but if you have any ideas, feel free to push/suggest a fix.

**Comment by renkun-ken** [comment]
>I added a command button to the entry Install CRAN Package (I felt it fits better there, since the other commands next to Help topics by Package only affect the tree view but don't install/modify any actual packages).

Yes, makes good sense.

>As you suggested, the command executes update.packages(ask=FALSE, repos=<CRAN_URL>). On my machine this worked for most packages but some packages seem to cause problems. I think this is caused by them being loaded somewhere, so that their .DLL files cannot be overwritten. I don't think there is a simple solution for this, so I wouldn't try to fix this, but if you have any ideas, feel free to push/suggest a fix.

I think it is a known issue in Windows. I guess we could leave it as is at the moment.

**Review by renkun-ken — APPROVED** [review]
LGTM

**Pull request merged**
