### PR TITLE
Support single quote (Fix #260)

### LINKED ISSUE #260: [Feature request] "Surround" support in RMarkdown files
Even though I mostly use vim-surround, I noticed that there is no native "surround" support for R within vscode by default (i.e. not in vim mode).

Seems like this needs to be added on a [per language base](https://stackoverflow.com/questions/42363030/visual-studio-code-surround-with).

### PR DESCRIPTION
**Pull request by Ikuyadeu**
**What problem did you solve?**
Fix #260
@andycraig If you like it, could you merge this PR?
**(If you have)Screenshot**
singlequote

**(If you do not have screenshot) How can I check this pull request?**

### CODE REVIEW

**Comment by andycraig** [comment]
@Ikuyadeu Sure, I will check.

@Ikuyadeu @renkun-ken The ‘build’ CI check is failing but I don’t think it should be affected by this PR. Is it okay?

**Comment by renkun-ken** [comment]
The build failure starts from `eslint` merged to `master`.

https://github.com/Ikuyadeu/vscode-R/pull/264/checks?check_run_id=529908682#step:5:8

We may have to fix this later.

I'm also wondering if we should also add backtick?

**Comment by Ikuyadeu** [comment]
@andycraig 
I agree with you. Clean up is another work.
As the next, we needs change GitHub Action tslint to eslint (I updated related issue https://github.com/Ikuyadeu/vscode-R/issues/215)

@renkun-ken  Ok, I added back tips.

**Comment by andycraig** [comment]
@Ikuyadeu @renkun-ken I have tested this on Windows 10 and it works (single quotes and backticks).

@renkun-ken I just re-ran CI and `build` still fails although #265 is closed. If that's not a problem, can you merge this? Thank you.

**Comment by renkun-ken** [comment]
I test this on Ubuntu and macOS and it works.

The CI build fails because this branch is still based on tslint. When it is merged to master, the build should succeed.

**Comment by Ikuyadeu** [comment]
@andycraig @renkun-ken Thank you for your testing and review!

**Comment by renkun-ken** [comment]
BTW, I also took a look at whether it works in Rmd by typing double quotes, single quotes and backticks, but none of them seem to work. I'm not sure if we should do anything about it? I thought it should work since the Rmd uses r language in code chunks.

**Comment by andycraig** [comment]
@renkun-ken Yep, that's why I re-opened #260. I have a fix for it, I'll do a PR for it and another couple of issues this weekend.

**Pull request merged**
