### PR TITLE
WIP Cleaning the project code for eslint (Fix  #215)

### LINKED ISSUE #215: Clean up the project
This project needs to be clean up the whole of files for future contributors.

* [x] Rewriting the contribution guide(`CONTRIBUTING.md`)
* [x] Updating tslint to eslint
* [x] Applying GitHub Action for the Pull Request for eslint (solved by #266)
  * https://github.com/marketplace/actions/setup-node-js-for-use-with-actions looks good that have not only eslint function
  * (Next workaround) https://github.com/marketplace/actions/eslint-action that is simple but only eslint function
* [x] Following the eslint
* [x] Redefining eslint rules
* [ ] Minimizing each function and dependency
* [x] (My selfish opinion) Applying the [DevReplay](https://devreplay.github.io/) that is implemented by me.

### PR DESCRIPTION
**Pull request by Ikuyadeu**
**What problem did you solve?**

Close #215

**How can I check this pull request?**

1. Get the tslint
```
sodo npm install -g eslint
```
2. Install the [eslint extensions](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
3. Edit the `.eslintrc.json`
3. You can see remained warnings

### CODE REVIEW

**Comment by renkun-ken** [comment]
When I install `tslint` it says

```
deprecate tslint@^6.0.0 TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
```

Is there anything that we should do about it?

**Comment by Ikuyadeu** [comment]
@renkun-ken OK, I updated to eslint.

**Comment by Ikuyadeu** [comment]
I once close this for the conflict.
BTW, @renkun-ken could you use the tslint plugin? It is still useful for maintenance work even it is deprecated.

**Comment by renkun-ken** [comment]
OK, thanks for the reminding!

The default linting still reports a lot of problems with latest `master` as the following images shows. Do we ignore them?

image

**Comment by Ikuyadeu** [comment]
@renkun-ken  Thank you for taking care, I appreciate your large contributions.

I think it should be fixed except `no-magic-number` and `no-console`. Other warnings have solutions in the [tslint docs](https://palantir.github.io/tslint/rules/no-floating-promises/).

So, could you take care of the small warnings such as `max-line-length`, `prefer-switch`, `newline-per-chained-call`, `prefer-template`, and semi-colon from the next pull request?
Also, you can change the [rule file](https://github.com/Ikuyadeu/vscode-R/blob/master/tslint.json) is some rules are not fit to our project.

I will fix large scale warnings (`no-unsafe-any` and `no-floating-promises`) in the future.

**Comment by renkun-ken** [comment]
@Ikuyadeu Thanks for your information. I'll take care of the linting.

BTW, we may set up some GitHub Actions to perform the linting on PR automatically so that the lines that do not follow the rules would be annotated in the PR diff view.

**Comment by Ikuyadeu** [comment]
@renkun-ken It is a good idea! I will update #215 list.

**Pull request closed without merging**
