### PR TITLE
Add R Markdown surround and frontmatter comments

### LINKED ISSUE #249: Wrong comment type in RMarkdown YAML frontmatter
@andycraig, I think I found an issue with the latest commit related to comments. It provides `R` `#` comments in r-chunks, and `html` comments in `markdown`, however in the `yaml` header, it also uses `html` comments, instead of the `#` ones. Is this behaviour expected?

image

_Originally posted by @atanasj in https://github.com/Ikuyadeu/vscode-R/issues/238#issuecomment-591088069_

### LINKED ISSUE #260: [Feature request] "Surround" support in RMarkdown files
Even though I mostly use vim-surround, I noticed that there is no native "surround" support for R within vscode by default (i.e. not in vim mode).

Seems like this needs to be added on a [per language base](https://stackoverflow.com/questions/42363030/visual-studio-code-surround-with).

### PR DESCRIPTION
**Pull request by andycraig**
Fixes #249 

Fixes #260 

This PR includes third-party code. The new lines in package.json are copied from
https://github.com/microsoft/vscode/blob/master/extensions/markdown-basics/package.json
which is MIT-licensed. The license information is included in
`ThirdPartyNotices.txt`. License information cannot be added to
`package.json` because JSON does not allow comments. I also added these lines in 1f355a38f00c51e88669001b22c3c2f1eedf6ff8, and then removed them in 4a108e1fc1c673d3fd3746128cbf1b63747b0984. I didn't include the license information that time but I think I should have. I copied the format of `ThirdPartyNotices.txt` from https://github.com/microsoft/vscode/blob/master/ThirdPartyNotices.txt

@Ikuyadeu I have put your name in `ThirdPartyNotices.txt` - please check that it is okay.

**What problem did you solve?**

Adds surround support for R Markdown files.

Adds backtick surround and completion for R Markdown and R documentation files.

Adds correct comments for R Markdown YAML frontmatter, and other languages already supported by VSCode markdown.

**How can I check this pull request?**

**Comments in R Markdown YAML frontmatter:** Place cursor in YAML frontmatter. Use command `Toggle Line Comment`. Previously: Comment is HTML comment `<!-- -->`. Now: Comment is YAML comment `#`.

**Surround in R Markdown:** In R Markdown file, select a word. Press `'`. Previously: Word is replaced by `'`. Now: Word is surrounded by `'`.

**Backticks in R Markdown/R document files:** Select a word. Press backtick. Previously: Word is replaced by backtick. Now: Word is surrounded by backticks.

### CODE REVIEW

**Comment by renkun-ken** [comment]
I test this on macOS.

**Commenting**

Commenting works nicely in 

* YAML frontmatter, markdown content
* Rmd R code chunk (\`\`\`{r})
* Rmd C++ code chunk (\`\`\`{cpp})
* Markdown R code chunk (\`\`\`r)
* Markdown C++ code chunk (\`\`\`cpp)

but do not work with python code chunks (treating it like markdown content)

* Rmd Python code chunk (\`\`\`{python})
* Markdown R code chunk (\`\`\`python)

Although this is not covered by this PR but it still seems worthy pointing out as RStudio supports many language chunks in Rmd.

**Surround in R Markdown**

The surrounding of quotes works well.

**Backticks in R Markdown/R document files**

The backticks works well but introduces an obvious drawback: Typing backticks to create a code chunk will never end up with three backticks but two or four.

**Extra things to notice**

It looks the languageserver diagnostics will fail with Rmd that contains markdown code chunk of any language (\`\`\`anything). Will raise an issue at languageserver.

**Comment by Ikuyadeu** [comment]
@andycraig Thank you for your pull request.
The `ThirdPartyNotices.txt` contents look good.

**Comment by andycraig** [comment]
@Ikuyadeu Great, thank you!

@renkun-ken Thank you for testing!

> but does not work with python code chunks (treating it like markdown content)
> 
> Rmd Python code chunk (```{python})
>
> Markdown R code chunk (```python)

I'll open a new issue for Rmd code chunks like ```{python}`.

For me on Windows 10, Python markdown code chunks like ```python _do_ work. That is, if I create a block

    ```python
    var
    ```

and use the `Toggle Line Comment` command, the comment is a Python `#`, not an HTML `<!-- -->`. When you try this, the comment is an HTML comment?

> The backticks works well but introduces an obvious drawback: Typing backticks to create a code chunk will never end up with three backticks but two or four.

Whoops, I missed that! I will add a commit to remove backticks from auto-closing pairs in R Markdown.

Thank you!

**Comment by renkun-ken** [comment]
@andycraig Sorry, my mistake, ```python works as expected, both highlighing and commenting.

The backtick not auto-closing looks good now.

Everything LGTM. If you have nothing more to add, please feel free to merge.

**Comment by andycraig** [comment]
@renkun-ken Thank you for the checks! I'll go ahead and merge now.

**Pull request merged**
