### PR TITLE
Enable default R location to be used on mac/linux if none is supplied

### PR DESCRIPTION
**Pull request by gowerc**
**What problem did you solve?**

#339 

**(If you do not have screenshot) How can I check this pull request?**

* Ensure R is on your search path
* open vscode with default settings and run "create new R terminal"
* a new R session should open
* change vscode default settings for R location on mac/linux to a null/junk location
*  run "create new R terminal"
* A error message should appear saying unable to open the terminal 

Please find a gif of the above below:

### CODE REVIEW

**Comment by gowerc** [comment]
Hey @andycraig  & @renkun-ken, Updated the PR to look for the path variable across all 3 OS's.  Works fine on my Mac but need someone to test it on windows as I don't have access to a windows machine sorry :(

**Comment by renkun-ken** [comment]
I test this on both macOS and Ubuntu and it works well. Maybe @andycraig could take a look at Windows.

**Comment by renkun-ken** [comment]
I test this on Windows 10 VM and it works as expected.

**Comment by Ikuyadeu** [comment]
@gowerc  Great works! These have a lot of great improvements. I will publish a new version this night.

**Pull request merged**
